apiVersion: v1
kind: ConfigMap
metadata:
  name: bot-amenity-java-config
data:
  BDK_BOT_PRIVATEKEY_PATH: rsa/private-key.pem
  BDK_BOT_USERNAME: dev2-ari-bot-1
  BDK_HOST: develop2.symphony.com
  BDK_AGENT_HOST: develop2.symphony.com
  BDK_POD_HOST: develop2.symphony.com
  BDK_KEYMANAGER_HOST: develop2.symphony.com
  LOGGING_LEVEL_COM_SYMPHONY: info