apiVersion: apps/v1
kind: Deployment
metadata:
  name: bot-amenity-java
spec:
  selector:
    matchLabels:
      app: bot-amenity-java
  template:
    spec:
      containers:
        - name: bot-amenity-java
          resources:
            requests:
              cpu: 20m
            limits:
              cpu: 100m
          envFrom:
            - configMapRef:
                name: bot-amenity-java-config