apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: bot-amenity-java-nsp
resources:
  - ../base
  - bot-config.yml
secretGenerator:
  - name: bot-amenity-java-private-key
    files:
      - private-key.pem
patches:
  - path: deployment.patch.yml