apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: bot-amenity-java-nsp
resources:
  - ../base
images:
  - name: LOCATION-docker.pkg.dev/PROJECT_ID/REPOSITORY/IMAGE:TAG
    newName: localhost:5000/bot-amenity-java-img
    newTag: latest
secretGenerator:
  - name: bot-amenity-java-private-key
    files:
      - privatekey.pem