bdk:
  host: develop2.symphony.com

  bot:
    username: dev2-ari-bot-1
    privateKey:
      path: rsa/privatekey.pem

#  host: sup.symphony.com

#  bot:
#    username: bot-amenity-java
#    privateKey:
#      path: rsa/sup/privatekey.pem

#  agent:
#    host: sup-agent.symphony.com

#  pod:
#    host: sup.symphony.com

#  keyManager:
#    host: sup-km.symphony.com


logging:
  level:
    com.symphony: debug
